# Generated by Django 2.1.15 on 2020-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Playerstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.CharField(max_length=255)),
                ('bowler_name', models.CharField(max_length=255)),
                ('batsman_name', models.CharField(max_length=255)),
                ('non_striker_name', models.CharField(max_length=255)),
                ('run_batsman', models.CharField(max_length=255)),
            ],
        ),
    ]
